version: '3.9'

services:
  rasa:
    image: rasa/rasa:main-full
    user: root
    # Ustawiamy jako entrypoint zwykły /bin/bash
    entrypoint: /bin/bash
    # 'command' definiujemy w formie listy, gdzie pierwszym elementem jest '-c',
    # a drugim jest nasz ciąg poleceń w Bashu.
    command:
      - "-c"
      - >-
        rasa train &&
        rasa run --connector botframework --credentials credentials.yml --port 5005 --enable-api --cors '*' --debug

    volumes:
      - ./:/app
    ports:
      - "5005:5005"

  action_server:
    image: rasa/rasa:3.6.2-full
    entrypoint: /bin/bash
    command:
      - "-c"
      - >-
        rasa run actions --debug --port 5055
    volumes:
      - ./:/app
    ports:
      - "5055:5055"
