version: '3.9'

services:
  rasa:
    image: rasa/rasa:3.6.2-full
    user: root
    entrypoint: /bin/bash
    command:
      - "-c"
      - >-
        rasa run --enable-api --cors "*" --debug


    volumes:
      - ./:/app
    ports:
      - "5005:5005"

  action_server:
    image: rasa/rasa:3.6.2-full
    entrypoint: /bin/bash
    command:
      - "-c"
      - >-
        rasa run actions --debug --port 5055
    volumes:
      - ./:/app
    ports:
      - "5055:5055"
